# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a8ddeeb7d8bd31870f505a3d8ac48468337e95d9b1c7d4333d654ec2e8119dd8730cdc5e70d2c633d63aaaa264452022f2e937dbf1fc0189e6980f8389a5030

test:
  secret_key_base: 6dd7a09b42408fb9ad4846c240986f258689a2f96a4c68656a3f579a4294fb41396a3319a8fefc0655e0c8539833fe99e126dcff3b5e313c8b5aebde701abfc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
